### PR TITLE
Discovery and Commands sort of

### PR DESCRIPTION
**Pull request by amaierhofer**
Hi, 

I have done some work on this lately and just wondered if you have any interest in pulling some of it. The discovery plugin is most stable imho. I tried to provide some tests for this also. I am willing to rework some of you suggest improvements.

### CODE REVIEW

**Comment by metajack** [comment]
The code is not organized anything like the other plugins. Can you explain that a bit?

Also, the first commit is modifying a file that is not in the master of my repo. Is there a bit missing here?

I'm sure we can work out the issues and get these merged.

**Comment by metajack** [comment]
Whoops. Clicked the wrong button there. :)

**Comment by amaierhofer** [comment]
code organisation is due to the test framework I was using (jasmine on top of nodejs). At the time I was using it it forced that structure on you, but i think it has changed. I will try to clean this up a bit and create a single branch for disco. When ready I will send you another request. Just wanted to see if you are alive basically ;)

**Comment by metajack** [comment]
I'm slow, but live :)

On Tue, May 10, 2011 at 2:42 AM, amaierhofer
reply@reply.github.com
wrote:

**Pull request closed without merging**
