### PR TITLE
Initial SI File Transfer implementation

### PR DESCRIPTION
**Pull request by arlolra**
uses the IBB plugin

### CODE REVIEW

**Comment by anomepani** [comment]
In strophe.si-filetransfer.js plugin what is the meaning of  init method's parameter _c and _cb ?

**Comment by arlolra** [comment]
`_c` is the connection. `_cb` is the callback to fire when receiving a stream initiation. The callback can be attached with the `addFileHandler()` method.

**Comment by anomepani** [comment]
Thank you Arlo Breault for replying me. I have also one issue related to
this,using  stroph.si-filetransfer.js plugin how can we accept or cancel
file transfer initiation in html ,like when file transfer is initiation
receiver party have to accept this file transfer and after that transfer is
done. how can we implement this scenario in html ?

**Comment by anomepani** [comment]
what is the significance of <code>addFileHandler()</code> in strophe.si-filetransfer.js ? how can we use in html based client for receiving file ?

**Comment by anomepani** [comment]
When I am sending file using <code>strophe.si-filetransfer.js</code> and <code>strophe.ibb.js</code> this two plugin ,while sending file from <code>html client</code> failure occur and <code>error code is 503</code> in call back due to time out , but I don't understand what is the issue ?

**Comment by arlolra** [comment]
@anomepani Is your code online somewhere?

`addFileHandler` is used to attach a callback to run when receiving a stream initiation.

You may want to look at how CryptoCat uses these files,
https://github.com/cryptocat/cryptocat/blob/master/src/core/js/etc/fileTransfer.js

**Comment by anomepani** [comment]
@arlolra  thank you. This is what i wanted

**Comment by anomepani** [comment]
@arlolra , I have seen that when we login to xmpp server using jid(jabber id) after successful login our <code>connection.jid</code> and our login<code>jid</code> is difference some extra information is added like <code>jid@somedomain/randomvalue</code>.
I want to know that is that extra part and what is the significance of that in xmpp chat.

**Comment by anomepani** [comment]
@metajack, @arlolra ,I have confusion about text sending and file sending in xmpp client in web based client.
Please Help me to guide about this problem.
  What is the difference between simple text sending and file transfer in xmpp client.? 

Is it possible to send file to offline user ?

**Comment by arlolra** [comment]
> What is the difference between simple text sending and file transfer in xmpp client.?

Text sending is the default. File transfers are something separate that need to be negotiated.

> Is it possible to send file to offline user ?

You might want to see, http://xmpp.org/extensions/xep-0160.html

> I have seen that when we login to xmpp server using jid(jabber id) after successful login our connection.jid and our loginjid is difference some extra information is added like jid@somedomain/randomvalue.
> I want to know that is that extra part and what is the significance of that in xmpp chat.

I'm not sure. I think you'd be better served opening an issue here, https://github.com/strophe/strophejs/issues

**Comment by anomepani** [comment]
@arlolra ,Thank you for replying.

**Pull request merged**
