### PR TITLE
Fixed problem where a subscription type presence stanza caused roster pl...

### PR DESCRIPTION
**Pull request by hperrin**
...ugin to create a null resource. Also fixed a typo that caused new groups data to be placed in a "group" property instead.

### CODE REVIEW

**Comment by hperrin** [comment]
Are you guys gonna pull these, or should I just keep my own fork? I have a lot more improvements waiting.

**Comment by hperrin** [comment]
This is ridiculous. It's been almost 3 weeks. Is this project dead?

**Comment by flosse** [comment]
No this project is not dead. All the work here is done in our spare time so please be patient.
There are some merge conflicts within this pull request. Would you mind to fix that?

**Comment by hperrin** [comment]
I submitted a fixed version:
https://github.com/metajack/strophejs-plugins/pull/79

I'm going to close this request. I understand that this isn't a high priority, but more than a month without even a comment on a bugfix makes me not want to bother submitting. The project may not be dead, but I wouldn't consider it active. I have some more features to submit, so I'll send a pull request after you merge this one.

**Pull request closed without merging**
