### PR TITLE
Entity Capabilities Plugin (XEP-0115)

### PR DESCRIPTION
**Pull request by mweibel**
Hi,

I developed the entity capabilities plugin on top of the disco plugin.
The recently added sha-1.js of strophe.js is required in order for the plugin to work.
- Michael

### CODE REVIEW

**Comment by flosse** [comment]
Hi Michael,
thanks for your work!
Did you have a look at the existing CAPS plugin (https://github.com/flosse/strophejs-plugins/tree/master/caps)?
However, Yours looks pretty good and much more complete.
Which disco plugin do you use (there are two)?

**Comment by mweibel** [comment]
Hi flosse,

oh, no didn't see yours :) Could have saved me some time ;)
Well yours seem to add some adapter-methods for the disco-plugin. Maybe that's not a bad idea. 
Also using the module pattern seems to be a good idea.

I didn't see two (although I saw your open issue).. I use [this one](https://github.com/metajack/strophejs-plugins/blob/master/disco/strophe.disco.js) which is the other one?

I'll need to do some fixes, at a 2nd glance I saw some missing this's :)

**Comment by flosse** [comment]
I updated #42 so that it's more visible that there are two disco plugins ;-)

**Comment by flosse** [comment]
... and if you like to have some fun you could write some tests and merge the two caps plugins ;-)  => #47

**Comment by mweibel** [comment]
Thanks for merging!

**Pull request merged**
