### PR TITLE
making XmppRoom handlers instance fields rather then class fields

### PR DESCRIPTION
**Pull request by dmytrolev**
this fix is about making handlers stored in each XmppRoom individually for not notifying all the rooms about presence or message happening in one of them.
this patch is very small (coffeescript part, about js - i don't understand why does it differ so much) and i should have taken care of _handler_ids, but for now i would like to know your opinion on this kind of change - maybe i misunderstand the idea behind this kind of handlers storing
thank you

### CODE REVIEW

**Comment by flosse** [comment]
@gordin Would you mind to look at this fix?

@dimalev 
Thanks &

> i don't understand why does it differ so much

This is because the previous JS version was compiled with the `bare` option: `coffee -cb file.coffee` instead of `coffee -c file.coffee`.

**Comment by Gordin** [comment]
@flosse @dimalev The idea behind this handler storing was to not have to attach a handler for every single MUC to the global handler chain as this would mean that EVERY stanza is checked against every MUC channel. This way there is one global handler that catches MUC related stanzas and forwards them only to MUC handlers.

I didn't test this but it looks fine to me. My logic actually assumes the handlers to be instance fields and only dispatches to handlers for one room, but because CoffeeScript does some magic it also works on class fields...
(I made a bug, I think what you did fixed it.)

Did you test if you can be in multiple rooms with different handlers and they work as intended? If so, I'm for merging this.

**Comment by flosse** [comment]
BTW: What about writing some tests?

**Comment by benzimmer** [comment]
Just tested this, because I encountered a strange error, which always passed the last joined XmppRoom into the callbacks for every joined room.
For example presence updates for room1 where passed into the presence callback with the XmppRoom for room2.

This patch fixes this particular error for me and seems to work fine in all other regards I've tested.

**Comment by dmytrolev** [comment]
how do you do tests?

**Comment by flosse** [comment]
> how do you do tests?

There are several test frameworks. Just use one you like. One of my favorite is [buster.js](http://busterjs.org/) because you can run your tests in real browsers from the command line simultaneously.
Also have a look at existing strophe-plugin tests if you don't know how to start.

**Comment by dmytrolev** [comment]
hi, sorry for long delay
i added buster tests - those can be run from muc/ folder, also there has to be strophe.min.js there. i made browser test - for making nodejs test looks for me impossible - i have no idea how can one make good strophe mock.
thanks

**Comment by flosse** [comment]
@Gordin I think its your turn ;-) Just let me know if we can merge it.
@dimalev thx

**Comment by dmytrolev** [comment]
what do you guys use for documentaion?
and will branch this ever merged?

**Comment by flosse** [comment]
@dimalev 

> what do you guys use for documentaion?

I think the best way is to use plain text / markdown within the README

> and will branch this ever merged?

@Gordin, @jcbrand: do you agree with the patches?

**Comment by dmytrolev** [comment]
I've already found, docs tool is NaturalDoc.

**Comment by jcbrand** [comment]
@flosse @Gordin I'm happy with the change, it's basically the same as what I suggested in Pull Request #90

**Pull request merged**
